# Generated by Django 5.1.1 on 2024-09-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ("id", "checkin")},
        ),
        migrations.AlterField(
            model_name="booking",
            name="checkin",
            field=models.DateField(db_index=True, verbose_name="Check-In"),
        ),
    ]
